/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TributosRouteImport } from './routes/tributos'
import { Route as TesourariaRouteImport } from './routes/tesouraria'
import { Route as RhRouteImport } from './routes/rh'
import { Route as ProtocoloRouteImport } from './routes/protocolo'
import { Route as PortalFinanceiroRouteImport } from './routes/portal-financeiro'
import { Route as PontoRouteImport } from './routes/ponto'
import { Route as PatrimonioRouteImport } from './routes/patrimonio'
import { Route as OuvidoriaRouteImport } from './routes/ouvidoria'
import { Route as OrdensBancariasRouteImport } from './routes/ordens-bancarias'
import { Route as OrcamentoRouteImport } from './routes/orcamento'
import { Route as MeusDocumentosRouteImport } from './routes/meus-documentos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LicitacoesRouteImport } from './routes/licitacoes'
import { Route as GestorRouteImport } from './routes/gestor'
import { Route as FrotasRouteImport } from './routes/frotas'
import { Route as EsicRouteImport } from './routes/esic'
import { Route as ControleInternoRouteImport } from './routes/controle-interno'
import { Route as ContratosRouteImport } from './routes/contratos'
import { Route as BalancosRouteImport } from './routes/balancos'
import { Route as AppRouteImport } from './routes/app'
import { Route as AlmoxarifadoRouteImport } from './routes/almoxarifado'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RhVtVaRouteImport } from './routes/rh.vt-va'
import { Route as RhTabelasFiscaisRouteImport } from './routes/rh.tabelas-fiscais'
import { Route as RhSimulacoesRouteImport } from './routes/rh.simulacoes'
import { Route as RhRubricasRouteImport } from './routes/rh.rubricas'
import { Route as RhPrevidenciaRouteImport } from './routes/rh.previdencia'
import { Route as RhPessoasRouteImport } from './routes/rh.pessoas'
import { Route as RhMovimentacoesRouteImport } from './routes/rh.movimentacoes'
import { Route as RhImportacoesRouteImport } from './routes/rh.importacoes'
import { Route as RhFuncionariosRouteImport } from './routes/rh.funcionarios'
import { Route as RhFolhasEspeciaisRouteImport } from './routes/rh.folhas-especiais'
import { Route as RhFeriasRouteImport } from './routes/rh.ferias'
import { Route as RhFamiliaRouteImport } from './routes/rh.familia'
import { Route as RhEventosFuncionaisRouteImport } from './routes/rh.eventos-funcionais'
import { Route as RhEscalasRouteImport } from './routes/rh.escalas'
import { Route as RhCiclosRouteImport } from './routes/rh.ciclos'
import { Route as GestorLrfRouteImport } from './routes/gestor/lrf'
import { Route as GestorAssistenteRouteImport } from './routes/gestor/assistente'
import { Route as ContaSegurancaRouteImport } from './routes/conta.seguranca'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminSegurancaRouteImport } from './routes/admin.seguranca'
import { Route as AdminMigracaoHistoricaRouteImport } from './routes/admin/migracao-historica'
import { Route as AdminEstruturaRouteImport } from './routes/admin.estrutura'
import { Route as AdminDataMartRouteImport } from './routes/admin/data-mart'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminAuditoriaRouteImport } from './routes/admin.auditoria'
import { Route as RhFuncionariosIdRouteImport } from './routes/rh.funcionarios.$id'

const TributosRoute = TributosRouteImport.update({
  id: '/tributos',
  path: '/tributos',
  getParentRoute: () => rootRouteImport,
} as any)
const TesourariaRoute = TesourariaRouteImport.update({
  id: '/tesouraria',
  path: '/tesouraria',
  getParentRoute: () => rootRouteImport,
} as any)
const RhRoute = RhRouteImport.update({
  id: '/rh',
  path: '/rh',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocoloRoute = ProtocoloRouteImport.update({
  id: '/protocolo',
  path: '/protocolo',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalFinanceiroRoute = PortalFinanceiroRouteImport.update({
  id: '/portal-financeiro',
  path: '/portal-financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const PontoRoute = PontoRouteImport.update({
  id: '/ponto',
  path: '/ponto',
  getParentRoute: () => rootRouteImport,
} as any)
const PatrimonioRoute = PatrimonioRouteImport.update({
  id: '/patrimonio',
  path: '/patrimonio',
  getParentRoute: () => rootRouteImport,
} as any)
const OuvidoriaRoute = OuvidoriaRouteImport.update({
  id: '/ouvidoria',
  path: '/ouvidoria',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdensBancariasRoute = OrdensBancariasRouteImport.update({
  id: '/ordens-bancarias',
  path: '/ordens-bancarias',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentoRoute = OrcamentoRouteImport.update({
  id: '/orcamento',
  path: '/orcamento',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusDocumentosRoute = MeusDocumentosRouteImport.update({
  id: '/meus-documentos',
  path: '/meus-documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LicitacoesRoute = LicitacoesRouteImport.update({
  id: '/licitacoes',
  path: '/licitacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const GestorRoute = GestorRouteImport.update({
  id: '/gestor',
  path: '/gestor',
  getParentRoute: () => rootRouteImport,
} as any)
const FrotasRoute = FrotasRouteImport.update({
  id: '/frotas',
  path: '/frotas',
  getParentRoute: () => rootRouteImport,
} as any)
const EsicRoute = EsicRouteImport.update({
  id: '/esic',
  path: '/esic',
  getParentRoute: () => rootRouteImport,
} as any)
const ControleInternoRoute = ControleInternoRouteImport.update({
  id: '/controle-interno',
  path: '/controle-interno',
  getParentRoute: () => rootRouteImport,
} as any)
const ContratosRoute = ContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => rootRouteImport,
} as any)
const BalancosRoute = BalancosRouteImport.update({
  id: '/balancos',
  path: '/balancos',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AlmoxarifadoRoute = AlmoxarifadoRouteImport.update({
  id: '/almoxarifado',
  path: '/almoxarifado',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RhVtVaRoute = RhVtVaRouteImport.update({
  id: '/vt-va',
  path: '/vt-va',
  getParentRoute: () => RhRoute,
} as any)
const RhTabelasFiscaisRoute = RhTabelasFiscaisRouteImport.update({
  id: '/tabelas-fiscais',
  path: '/tabelas-fiscais',
  getParentRoute: () => RhRoute,
} as any)
const RhSimulacoesRoute = RhSimulacoesRouteImport.update({
  id: '/simulacoes',
  path: '/simulacoes',
  getParentRoute: () => RhRoute,
} as any)
const RhRubricasRoute = RhRubricasRouteImport.update({
  id: '/rubricas',
  path: '/rubricas',
  getParentRoute: () => RhRoute,
} as any)
const RhPrevidenciaRoute = RhPrevidenciaRouteImport.update({
  id: '/previdencia',
  path: '/previdencia',
  getParentRoute: () => RhRoute,
} as any)
const RhPessoasRoute = RhPessoasRouteImport.update({
  id: '/pessoas',
  path: '/pessoas',
  getParentRoute: () => RhRoute,
} as any)
const RhMovimentacoesRoute = RhMovimentacoesRouteImport.update({
  id: '/movimentacoes',
  path: '/movimentacoes',
  getParentRoute: () => RhRoute,
} as any)
const RhImportacoesRoute = RhImportacoesRouteImport.update({
  id: '/importacoes',
  path: '/importacoes',
  getParentRoute: () => RhRoute,
} as any)
const RhFuncionariosRoute = RhFuncionariosRouteImport.update({
  id: '/funcionarios',
  path: '/funcionarios',
  getParentRoute: () => RhRoute,
} as any)
const RhFolhasEspeciaisRoute = RhFolhasEspeciaisRouteImport.update({
  id: '/folhas-especiais',
  path: '/folhas-especiais',
  getParentRoute: () => RhRoute,
} as any)
const RhFeriasRoute = RhFeriasRouteImport.update({
  id: '/ferias',
  path: '/ferias',
  getParentRoute: () => RhRoute,
} as any)
const RhFamiliaRoute = RhFamiliaRouteImport.update({
  id: '/familia',
  path: '/familia',
  getParentRoute: () => RhRoute,
} as any)
const RhEventosFuncionaisRoute = RhEventosFuncionaisRouteImport.update({
  id: '/eventos-funcionais',
  path: '/eventos-funcionais',
  getParentRoute: () => RhRoute,
} as any)
const RhEscalasRoute = RhEscalasRouteImport.update({
  id: '/escalas',
  path: '/escalas',
  getParentRoute: () => RhRoute,
} as any)
const RhCiclosRoute = RhCiclosRouteImport.update({
  id: '/ciclos',
  path: '/ciclos',
  getParentRoute: () => RhRoute,
} as any)
const GestorLrfRoute = GestorLrfRouteImport.update({
  id: '/lrf',
  path: '/lrf',
  getParentRoute: () => GestorRoute,
} as any)
const GestorAssistenteRoute = GestorAssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => GestorRoute,
} as any)
const ContaSegurancaRoute = ContaSegurancaRouteImport.update({
  id: '/conta/seguranca',
  path: '/conta/seguranca',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/admin/usuarios',
  path: '/admin/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSegurancaRoute = AdminSegurancaRouteImport.update({
  id: '/admin/seguranca',
  path: '/admin/seguranca',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMigracaoHistoricaRoute = AdminMigracaoHistoricaRouteImport.update({
  id: '/admin/migracao-historica',
  path: '/admin/migracao-historica',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEstruturaRoute = AdminEstruturaRouteImport.update({
  id: '/admin/estrutura',
  path: '/admin/estrutura',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDataMartRoute = AdminDataMartRouteImport.update({
  id: '/admin/data-mart',
  path: '/admin/data-mart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/admin/configuracoes',
  path: '/admin/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditoriaRoute = AdminAuditoriaRouteImport.update({
  id: '/admin/auditoria',
  path: '/admin/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const RhFuncionariosIdRoute = RhFuncionariosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RhFuncionariosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/almoxarifado': typeof AlmoxarifadoRoute
  '/app': typeof AppRoute
  '/balancos': typeof BalancosRoute
  '/contratos': typeof ContratosRoute
  '/controle-interno': typeof ControleInternoRoute
  '/esic': typeof EsicRoute
  '/frotas': typeof FrotasRoute
  '/gestor': typeof GestorRouteWithChildren
  '/licitacoes': typeof LicitacoesRoute
  '/login': typeof LoginRoute
  '/meus-documentos': typeof MeusDocumentosRoute
  '/orcamento': typeof OrcamentoRoute
  '/ordens-bancarias': typeof OrdensBancariasRoute
  '/ouvidoria': typeof OuvidoriaRoute
  '/patrimonio': typeof PatrimonioRoute
  '/ponto': typeof PontoRoute
  '/portal-financeiro': typeof PortalFinanceiroRoute
  '/protocolo': typeof ProtocoloRoute
  '/rh': typeof RhRouteWithChildren
  '/tesouraria': typeof TesourariaRoute
  '/tributos': typeof TributosRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/data-mart': typeof AdminDataMartRoute
  '/admin/estrutura': typeof AdminEstruturaRoute
  '/admin/migracao-historica': typeof AdminMigracaoHistoricaRoute
  '/admin/seguranca': typeof AdminSegurancaRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/conta/seguranca': typeof ContaSegurancaRoute
  '/gestor/assistente': typeof GestorAssistenteRoute
  '/gestor/lrf': typeof GestorLrfRoute
  '/rh/ciclos': typeof RhCiclosRoute
  '/rh/escalas': typeof RhEscalasRoute
  '/rh/eventos-funcionais': typeof RhEventosFuncionaisRoute
  '/rh/familia': typeof RhFamiliaRoute
  '/rh/ferias': typeof RhFeriasRoute
  '/rh/folhas-especiais': typeof RhFolhasEspeciaisRoute
  '/rh/funcionarios': typeof RhFuncionariosRouteWithChildren
  '/rh/importacoes': typeof RhImportacoesRoute
  '/rh/movimentacoes': typeof RhMovimentacoesRoute
  '/rh/pessoas': typeof RhPessoasRoute
  '/rh/previdencia': typeof RhPrevidenciaRoute
  '/rh/rubricas': typeof RhRubricasRoute
  '/rh/simulacoes': typeof RhSimulacoesRoute
  '/rh/tabelas-fiscais': typeof RhTabelasFiscaisRoute
  '/rh/vt-va': typeof RhVtVaRoute
  '/rh/funcionarios/$id': typeof RhFuncionariosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/almoxarifado': typeof AlmoxarifadoRoute
  '/app': typeof AppRoute
  '/balancos': typeof BalancosRoute
  '/contratos': typeof ContratosRoute
  '/controle-interno': typeof ControleInternoRoute
  '/esic': typeof EsicRoute
  '/frotas': typeof FrotasRoute
  '/gestor': typeof GestorRouteWithChildren
  '/licitacoes': typeof LicitacoesRoute
  '/login': typeof LoginRoute
  '/meus-documentos': typeof MeusDocumentosRoute
  '/orcamento': typeof OrcamentoRoute
  '/ordens-bancarias': typeof OrdensBancariasRoute
  '/ouvidoria': typeof OuvidoriaRoute
  '/patrimonio': typeof PatrimonioRoute
  '/ponto': typeof PontoRoute
  '/portal-financeiro': typeof PortalFinanceiroRoute
  '/protocolo': typeof ProtocoloRoute
  '/rh': typeof RhRouteWithChildren
  '/tesouraria': typeof TesourariaRoute
  '/tributos': typeof TributosRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/data-mart': typeof AdminDataMartRoute
  '/admin/estrutura': typeof AdminEstruturaRoute
  '/admin/migracao-historica': typeof AdminMigracaoHistoricaRoute
  '/admin/seguranca': typeof AdminSegurancaRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/conta/seguranca': typeof ContaSegurancaRoute
  '/gestor/assistente': typeof GestorAssistenteRoute
  '/gestor/lrf': typeof GestorLrfRoute
  '/rh/ciclos': typeof RhCiclosRoute
  '/rh/escalas': typeof RhEscalasRoute
  '/rh/eventos-funcionais': typeof RhEventosFuncionaisRoute
  '/rh/familia': typeof RhFamiliaRoute
  '/rh/ferias': typeof RhFeriasRoute
  '/rh/folhas-especiais': typeof RhFolhasEspeciaisRoute
  '/rh/funcionarios': typeof RhFuncionariosRouteWithChildren
  '/rh/importacoes': typeof RhImportacoesRoute
  '/rh/movimentacoes': typeof RhMovimentacoesRoute
  '/rh/pessoas': typeof RhPessoasRoute
  '/rh/previdencia': typeof RhPrevidenciaRoute
  '/rh/rubricas': typeof RhRubricasRoute
  '/rh/simulacoes': typeof RhSimulacoesRoute
  '/rh/tabelas-fiscais': typeof RhTabelasFiscaisRoute
  '/rh/vt-va': typeof RhVtVaRoute
  '/rh/funcionarios/$id': typeof RhFuncionariosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/almoxarifado': typeof AlmoxarifadoRoute
  '/app': typeof AppRoute
  '/balancos': typeof BalancosRoute
  '/contratos': typeof ContratosRoute
  '/controle-interno': typeof ControleInternoRoute
  '/esic': typeof EsicRoute
  '/frotas': typeof FrotasRoute
  '/gestor': typeof GestorRouteWithChildren
  '/licitacoes': typeof LicitacoesRoute
  '/login': typeof LoginRoute
  '/meus-documentos': typeof MeusDocumentosRoute
  '/orcamento': typeof OrcamentoRoute
  '/ordens-bancarias': typeof OrdensBancariasRoute
  '/ouvidoria': typeof OuvidoriaRoute
  '/patrimonio': typeof PatrimonioRoute
  '/ponto': typeof PontoRoute
  '/portal-financeiro': typeof PortalFinanceiroRoute
  '/protocolo': typeof ProtocoloRoute
  '/rh': typeof RhRouteWithChildren
  '/tesouraria': typeof TesourariaRoute
  '/tributos': typeof TributosRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/data-mart': typeof AdminDataMartRoute
  '/admin/estrutura': typeof AdminEstruturaRoute
  '/admin/migracao-historica': typeof AdminMigracaoHistoricaRoute
  '/admin/seguranca': typeof AdminSegurancaRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/conta/seguranca': typeof ContaSegurancaRoute
  '/gestor/assistente': typeof GestorAssistenteRoute
  '/gestor/lrf': typeof GestorLrfRoute
  '/rh/ciclos': typeof RhCiclosRoute
  '/rh/escalas': typeof RhEscalasRoute
  '/rh/eventos-funcionais': typeof RhEventosFuncionaisRoute
  '/rh/familia': typeof RhFamiliaRoute
  '/rh/ferias': typeof RhFeriasRoute
  '/rh/folhas-especiais': typeof RhFolhasEspeciaisRoute
  '/rh/funcionarios': typeof RhFuncionariosRouteWithChildren
  '/rh/importacoes': typeof RhImportacoesRoute
  '/rh/movimentacoes': typeof RhMovimentacoesRoute
  '/rh/pessoas': typeof RhPessoasRoute
  '/rh/previdencia': typeof RhPrevidenciaRoute
  '/rh/rubricas': typeof RhRubricasRoute
  '/rh/simulacoes': typeof RhSimulacoesRoute
  '/rh/tabelas-fiscais': typeof RhTabelasFiscaisRoute
  '/rh/vt-va': typeof RhVtVaRoute
  '/rh/funcionarios/$id': typeof RhFuncionariosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/almoxarifado'
    | '/app'
    | '/balancos'
    | '/contratos'
    | '/controle-interno'
    | '/esic'
    | '/frotas'
    | '/gestor'
    | '/licitacoes'
    | '/login'
    | '/meus-documentos'
    | '/orcamento'
    | '/ordens-bancarias'
    | '/ouvidoria'
    | '/patrimonio'
    | '/ponto'
    | '/portal-financeiro'
    | '/protocolo'
    | '/rh'
    | '/tesouraria'
    | '/tributos'
    | '/admin/auditoria'
    | '/admin/configuracoes'
    | '/admin/data-mart'
    | '/admin/estrutura'
    | '/admin/migracao-historica'
    | '/admin/seguranca'
    | '/admin/usuarios'
    | '/conta/seguranca'
    | '/gestor/assistente'
    | '/gestor/lrf'
    | '/rh/ciclos'
    | '/rh/escalas'
    | '/rh/eventos-funcionais'
    | '/rh/familia'
    | '/rh/ferias'
    | '/rh/folhas-especiais'
    | '/rh/funcionarios'
    | '/rh/importacoes'
    | '/rh/movimentacoes'
    | '/rh/pessoas'
    | '/rh/previdencia'
    | '/rh/rubricas'
    | '/rh/simulacoes'
    | '/rh/tabelas-fiscais'
    | '/rh/vt-va'
    | '/rh/funcionarios/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/almoxarifado'
    | '/app'
    | '/balancos'
    | '/contratos'
    | '/controle-interno'
    | '/esic'
    | '/frotas'
    | '/gestor'
    | '/licitacoes'
    | '/login'
    | '/meus-documentos'
    | '/orcamento'
    | '/ordens-bancarias'
    | '/ouvidoria'
    | '/patrimonio'
    | '/ponto'
    | '/portal-financeiro'
    | '/protocolo'
    | '/rh'
    | '/tesouraria'
    | '/tributos'
    | '/admin/auditoria'
    | '/admin/configuracoes'
    | '/admin/data-mart'
    | '/admin/estrutura'
    | '/admin/migracao-historica'
    | '/admin/seguranca'
    | '/admin/usuarios'
    | '/conta/seguranca'
    | '/gestor/assistente'
    | '/gestor/lrf'
    | '/rh/ciclos'
    | '/rh/escalas'
    | '/rh/eventos-funcionais'
    | '/rh/familia'
    | '/rh/ferias'
    | '/rh/folhas-especiais'
    | '/rh/funcionarios'
    | '/rh/importacoes'
    | '/rh/movimentacoes'
    | '/rh/pessoas'
    | '/rh/previdencia'
    | '/rh/rubricas'
    | '/rh/simulacoes'
    | '/rh/tabelas-fiscais'
    | '/rh/vt-va'
    | '/rh/funcionarios/$id'
  id:
    | '__root__'
    | '/'
    | '/almoxarifado'
    | '/app'
    | '/balancos'
    | '/contratos'
    | '/controle-interno'
    | '/esic'
    | '/frotas'
    | '/gestor'
    | '/licitacoes'
    | '/login'
    | '/meus-documentos'
    | '/orcamento'
    | '/ordens-bancarias'
    | '/ouvidoria'
    | '/patrimonio'
    | '/ponto'
    | '/portal-financeiro'
    | '/protocolo'
    | '/rh'
    | '/tesouraria'
    | '/tributos'
    | '/admin/auditoria'
    | '/admin/configuracoes'
    | '/admin/data-mart'
    | '/admin/estrutura'
    | '/admin/migracao-historica'
    | '/admin/seguranca'
    | '/admin/usuarios'
    | '/conta/seguranca'
    | '/gestor/assistente'
    | '/gestor/lrf'
    | '/rh/ciclos'
    | '/rh/escalas'
    | '/rh/eventos-funcionais'
    | '/rh/familia'
    | '/rh/ferias'
    | '/rh/folhas-especiais'
    | '/rh/funcionarios'
    | '/rh/importacoes'
    | '/rh/movimentacoes'
    | '/rh/pessoas'
    | '/rh/previdencia'
    | '/rh/rubricas'
    | '/rh/simulacoes'
    | '/rh/tabelas-fiscais'
    | '/rh/vt-va'
    | '/rh/funcionarios/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlmoxarifadoRoute: typeof AlmoxarifadoRoute
  AppRoute: typeof AppRoute
  BalancosRoute: typeof BalancosRoute
  ContratosRoute: typeof ContratosRoute
  ControleInternoRoute: typeof ControleInternoRoute
  EsicRoute: typeof EsicRoute
  FrotasRoute: typeof FrotasRoute
  GestorRoute: typeof GestorRouteWithChildren
  LicitacoesRoute: typeof LicitacoesRoute
  LoginRoute: typeof LoginRoute
  MeusDocumentosRoute: typeof MeusDocumentosRoute
  OrcamentoRoute: typeof OrcamentoRoute
  OrdensBancariasRoute: typeof OrdensBancariasRoute
  OuvidoriaRoute: typeof OuvidoriaRoute
  PatrimonioRoute: typeof PatrimonioRoute
  PontoRoute: typeof PontoRoute
  PortalFinanceiroRoute: typeof PortalFinanceiroRoute
  ProtocoloRoute: typeof ProtocoloRoute
  RhRoute: typeof RhRouteWithChildren
  TesourariaRoute: typeof TesourariaRoute
  TributosRoute: typeof TributosRoute
  AdminAuditoriaRoute: typeof AdminAuditoriaRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminDataMartRoute: typeof AdminDataMartRoute
  AdminEstruturaRoute: typeof AdminEstruturaRoute
  AdminMigracaoHistoricaRoute: typeof AdminMigracaoHistoricaRoute
  AdminSegurancaRoute: typeof AdminSegurancaRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  ContaSegurancaRoute: typeof ContaSegurancaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tributos': {
      id: '/tributos'
      path: '/tributos'
      fullPath: '/tributos'
      preLoaderRoute: typeof TributosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tesouraria': {
      id: '/tesouraria'
      path: '/tesouraria'
      fullPath: '/tesouraria'
      preLoaderRoute: typeof TesourariaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rh': {
      id: '/rh'
      path: '/rh'
      fullPath: '/rh'
      preLoaderRoute: typeof RhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocolo': {
      id: '/protocolo'
      path: '/protocolo'
      fullPath: '/protocolo'
      preLoaderRoute: typeof ProtocoloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal-financeiro': {
      id: '/portal-financeiro'
      path: '/portal-financeiro'
      fullPath: '/portal-financeiro'
      preLoaderRoute: typeof PortalFinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ponto': {
      id: '/ponto'
      path: '/ponto'
      fullPath: '/ponto'
      preLoaderRoute: typeof PontoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patrimonio': {
      id: '/patrimonio'
      path: '/patrimonio'
      fullPath: '/patrimonio'
      preLoaderRoute: typeof PatrimonioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ouvidoria': {
      id: '/ouvidoria'
      path: '/ouvidoria'
      fullPath: '/ouvidoria'
      preLoaderRoute: typeof OuvidoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ordens-bancarias': {
      id: '/ordens-bancarias'
      path: '/ordens-bancarias'
      fullPath: '/ordens-bancarias'
      preLoaderRoute: typeof OrdensBancariasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamento': {
      id: '/orcamento'
      path: '/orcamento'
      fullPath: '/orcamento'
      preLoaderRoute: typeof OrcamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-documentos': {
      id: '/meus-documentos'
      path: '/meus-documentos'
      fullPath: '/meus-documentos'
      preLoaderRoute: typeof MeusDocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licitacoes': {
      id: '/licitacoes'
      path: '/licitacoes'
      fullPath: '/licitacoes'
      preLoaderRoute: typeof LicitacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestor': {
      id: '/gestor'
      path: '/gestor'
      fullPath: '/gestor'
      preLoaderRoute: typeof GestorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frotas': {
      id: '/frotas'
      path: '/frotas'
      fullPath: '/frotas'
      preLoaderRoute: typeof FrotasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esic': {
      id: '/esic'
      path: '/esic'
      fullPath: '/esic'
      preLoaderRoute: typeof EsicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controle-interno': {
      id: '/controle-interno'
      path: '/controle-interno'
      fullPath: '/controle-interno'
      preLoaderRoute: typeof ControleInternoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contratos': {
      id: '/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof ContratosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/balancos': {
      id: '/balancos'
      path: '/balancos'
      fullPath: '/balancos'
      preLoaderRoute: typeof BalancosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/almoxarifado': {
      id: '/almoxarifado'
      path: '/almoxarifado'
      fullPath: '/almoxarifado'
      preLoaderRoute: typeof AlmoxarifadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rh/vt-va': {
      id: '/rh/vt-va'
      path: '/vt-va'
      fullPath: '/rh/vt-va'
      preLoaderRoute: typeof RhVtVaRouteImport
      parentRoute: typeof RhRoute
    }
    '/rh/tabelas-fiscais': {
      id: '/rh/tabelas-fiscais'
      path: '/tabelas-fiscais'
      fullPath: '/rh/tabelas-fiscais'
      preLoaderRoute: typeof RhTabelasFiscaisRouteImport
      parentRoute: typeof RhRoute
    }
    '/rh/simulacoes': {
      id: '/rh/simulacoes'
      path: '/simulacoes'
      fullPath: '/rh/simulacoes'
      preLoaderRoute: typeof RhSimulacoesRouteImport
      parentRoute: typeof RhRoute
    }
    '/rh/rubricas': {
      id: '/rh/rubricas'
      path: '/rubricas'
      fullPath: '/rh/rubricas'
      preLoaderRoute: typeof RhRubricasRouteImport
      parentRoute: typeof RhRoute
    }
    '/rh/previdencia': {
      id: '/rh/previdencia'
      path: '/previdencia'
      fullPath: '/rh/previdencia'
      preLoaderRoute: typeof RhPrevidenciaRouteImport
      parentRoute: typeof RhRoute
    }
    '/rh/pessoas': {
      id: '/rh/pessoas'
      path: '/pessoas'
      fullPath: '/rh/pessoas'
      preLoaderRoute: typeof RhPessoasRouteImport
      parentRoute: typeof RhRoute
    }
    '/rh/movimentacoes': {
      id: '/rh/movimentacoes'
      path: '/movimentacoes'
      fullPath: '/rh/movimentacoes'
      preLoaderRoute: typeof RhMovimentacoesRouteImport
      parentRoute: typeof RhRoute
    }
    '/rh/importacoes': {
      id: '/rh/importacoes'
      path: '/importacoes'
      fullPath: '/rh/importacoes'
      preLoaderRoute: typeof RhImportacoesRouteImport
      parentRoute: typeof RhRoute
    }
    '/rh/funcionarios': {
      id: '/rh/funcionarios'
      path: '/funcionarios'
      fullPath: '/rh/funcionarios'
      preLoaderRoute: typeof RhFuncionariosRouteImport
      parentRoute: typeof RhRoute
    }
    '/rh/folhas-especiais': {
      id: '/rh/folhas-especiais'
      path: '/folhas-especiais'
      fullPath: '/rh/folhas-especiais'
      preLoaderRoute: typeof RhFolhasEspeciaisRouteImport
      parentRoute: typeof RhRoute
    }
    '/rh/ferias': {
      id: '/rh/ferias'
      path: '/ferias'
      fullPath: '/rh/ferias'
      preLoaderRoute: typeof RhFeriasRouteImport
      parentRoute: typeof RhRoute
    }
    '/rh/familia': {
      id: '/rh/familia'
      path: '/familia'
      fullPath: '/rh/familia'
      preLoaderRoute: typeof RhFamiliaRouteImport
      parentRoute: typeof RhRoute
    }
    '/rh/eventos-funcionais': {
      id: '/rh/eventos-funcionais'
      path: '/eventos-funcionais'
      fullPath: '/rh/eventos-funcionais'
      preLoaderRoute: typeof RhEventosFuncionaisRouteImport
      parentRoute: typeof RhRoute
    }
    '/rh/escalas': {
      id: '/rh/escalas'
      path: '/escalas'
      fullPath: '/rh/escalas'
      preLoaderRoute: typeof RhEscalasRouteImport
      parentRoute: typeof RhRoute
    }
    '/rh/ciclos': {
      id: '/rh/ciclos'
      path: '/ciclos'
      fullPath: '/rh/ciclos'
      preLoaderRoute: typeof RhCiclosRouteImport
      parentRoute: typeof RhRoute
    }
    '/gestor/lrf': {
      id: '/gestor/lrf'
      path: '/lrf'
      fullPath: '/gestor/lrf'
      preLoaderRoute: typeof GestorLrfRouteImport
      parentRoute: typeof GestorRoute
    }
    '/gestor/assistente': {
      id: '/gestor/assistente'
      path: '/assistente'
      fullPath: '/gestor/assistente'
      preLoaderRoute: typeof GestorAssistenteRouteImport
      parentRoute: typeof GestorRoute
    }
    '/conta/seguranca': {
      id: '/conta/seguranca'
      path: '/conta/seguranca'
      fullPath: '/conta/seguranca'
      preLoaderRoute: typeof ContaSegurancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/seguranca': {
      id: '/admin/seguranca'
      path: '/admin/seguranca'
      fullPath: '/admin/seguranca'
      preLoaderRoute: typeof AdminSegurancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/migracao-historica': {
      id: '/admin/migracao-historica'
      path: '/admin/migracao-historica'
      fullPath: '/admin/migracao-historica'
      preLoaderRoute: typeof AdminMigracaoHistoricaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/estrutura': {
      id: '/admin/estrutura'
      path: '/admin/estrutura'
      fullPath: '/admin/estrutura'
      preLoaderRoute: typeof AdminEstruturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/data-mart': {
      id: '/admin/data-mart'
      path: '/admin/data-mart'
      fullPath: '/admin/data-mart'
      preLoaderRoute: typeof AdminDataMartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/admin/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/auditoria': {
      id: '/admin/auditoria'
      path: '/admin/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AdminAuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rh/funcionarios/$id': {
      id: '/rh/funcionarios/$id'
      path: '/$id'
      fullPath: '/rh/funcionarios/$id'
      preLoaderRoute: typeof RhFuncionariosIdRouteImport
      parentRoute: typeof RhFuncionariosRoute
    }
  }
}

interface GestorRouteChildren {
  GestorAssistenteRoute: typeof GestorAssistenteRoute
  GestorLrfRoute: typeof GestorLrfRoute
}

const GestorRouteChildren: GestorRouteChildren = {
  GestorAssistenteRoute: GestorAssistenteRoute,
  GestorLrfRoute: GestorLrfRoute,
}

const GestorRouteWithChildren =
  GestorRoute._addFileChildren(GestorRouteChildren)

interface RhFuncionariosRouteChildren {
  RhFuncionariosIdRoute: typeof RhFuncionariosIdRoute
}

const RhFuncionariosRouteChildren: RhFuncionariosRouteChildren = {
  RhFuncionariosIdRoute: RhFuncionariosIdRoute,
}

const RhFuncionariosRouteWithChildren = RhFuncionariosRoute._addFileChildren(
  RhFuncionariosRouteChildren,
)

interface RhRouteChildren {
  RhCiclosRoute: typeof RhCiclosRoute
  RhEscalasRoute: typeof RhEscalasRoute
  RhEventosFuncionaisRoute: typeof RhEventosFuncionaisRoute
  RhFamiliaRoute: typeof RhFamiliaRoute
  RhFeriasRoute: typeof RhFeriasRoute
  RhFolhasEspeciaisRoute: typeof RhFolhasEspeciaisRoute
  RhFuncionariosRoute: typeof RhFuncionariosRouteWithChildren
  RhImportacoesRoute: typeof RhImportacoesRoute
  RhMovimentacoesRoute: typeof RhMovimentacoesRoute
  RhPessoasRoute: typeof RhPessoasRoute
  RhPrevidenciaRoute: typeof RhPrevidenciaRoute
  RhRubricasRoute: typeof RhRubricasRoute
  RhSimulacoesRoute: typeof RhSimulacoesRoute
  RhTabelasFiscaisRoute: typeof RhTabelasFiscaisRoute
  RhVtVaRoute: typeof RhVtVaRoute
}

const RhRouteChildren: RhRouteChildren = {
  RhCiclosRoute: RhCiclosRoute,
  RhEscalasRoute: RhEscalasRoute,
  RhEventosFuncionaisRoute: RhEventosFuncionaisRoute,
  RhFamiliaRoute: RhFamiliaRoute,
  RhFeriasRoute: RhFeriasRoute,
  RhFolhasEspeciaisRoute: RhFolhasEspeciaisRoute,
  RhFuncionariosRoute: RhFuncionariosRouteWithChildren,
  RhImportacoesRoute: RhImportacoesRoute,
  RhMovimentacoesRoute: RhMovimentacoesRoute,
  RhPessoasRoute: RhPessoasRoute,
  RhPrevidenciaRoute: RhPrevidenciaRoute,
  RhRubricasRoute: RhRubricasRoute,
  RhSimulacoesRoute: RhSimulacoesRoute,
  RhTabelasFiscaisRoute: RhTabelasFiscaisRoute,
  RhVtVaRoute: RhVtVaRoute,
}

const RhRouteWithChildren = RhRoute._addFileChildren(RhRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlmoxarifadoRoute: AlmoxarifadoRoute,
  AppRoute: AppRoute,
  BalancosRoute: BalancosRoute,
  ContratosRoute: ContratosRoute,
  ControleInternoRoute: ControleInternoRoute,
  EsicRoute: EsicRoute,
  FrotasRoute: FrotasRoute,
  GestorRoute: GestorRouteWithChildren,
  LicitacoesRoute: LicitacoesRoute,
  LoginRoute: LoginRoute,
  MeusDocumentosRoute: MeusDocumentosRoute,
  OrcamentoRoute: OrcamentoRoute,
  OrdensBancariasRoute: OrdensBancariasRoute,
  OuvidoriaRoute: OuvidoriaRoute,
  PatrimonioRoute: PatrimonioRoute,
  PontoRoute: PontoRoute,
  PortalFinanceiroRoute: PortalFinanceiroRoute,
  ProtocoloRoute: ProtocoloRoute,
  RhRoute: RhRouteWithChildren,
  TesourariaRoute: TesourariaRoute,
  TributosRoute: TributosRoute,
  AdminAuditoriaRoute: AdminAuditoriaRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminDataMartRoute: AdminDataMartRoute,
  AdminEstruturaRoute: AdminEstruturaRoute,
  AdminMigracaoHistoricaRoute: AdminMigracaoHistoricaRoute,
  AdminSegurancaRoute: AdminSegurancaRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  ContaSegurancaRoute: ContaSegurancaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
