/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RhRouteImport } from './routes/rh'
import { Route as PortalFinanceiroRouteImport } from './routes/portal-financeiro'
import { Route as PontoRouteImport } from './routes/ponto'
import { Route as MeusDocumentosRouteImport } from './routes/meus-documentos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GestorRouteImport } from './routes/gestor'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RhVtVaRouteImport } from './routes/rh.vt-va'
import { Route as RhSimulacoesRouteImport } from './routes/rh.simulacoes'
import { Route as RhRubricasRouteImport } from './routes/rh.rubricas'
import { Route as RhPessoasRouteImport } from './routes/rh.pessoas'
import { Route as RhMovimentacoesRouteImport } from './routes/rh.movimentacoes'
import { Route as RhImportacoesRouteImport } from './routes/rh.importacoes'
import { Route as RhFuncionariosRouteImport } from './routes/rh.funcionarios'
import { Route as RhFolhasEspeciaisRouteImport } from './routes/rh.folhas-especiais'
import { Route as RhFeriasRouteImport } from './routes/rh.ferias'
import { Route as RhFamiliaRouteImport } from './routes/rh.familia'
import { Route as RhEventosFuncionaisRouteImport } from './routes/rh.eventos-funcionais'
import { Route as RhEscalasRouteImport } from './routes/rh.escalas'
import { Route as RhCiclosRouteImport } from './routes/rh.ciclos'
import { Route as GestorLrfRouteImport } from './routes/gestor/lrf'
import { Route as GestorAssistenteRouteImport } from './routes/gestor/assistente'
import { Route as ContaSegurancaRouteImport } from './routes/conta.seguranca'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminSegurancaRouteImport } from './routes/admin.seguranca'
import { Route as AdminMigracaoHistoricaRouteImport } from './routes/admin/migracao-historica'
import { Route as AdminEstruturaRouteImport } from './routes/admin.estrutura'
import { Route as AdminDataMartRouteImport } from './routes/admin/data-mart'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminAuditoriaRouteImport } from './routes/admin.auditoria'
import { Route as RhFuncionariosIdRouteImport } from './routes/rh.funcionarios.$id'

const RhRoute = RhRouteImport.update({
  id: '/rh',
  path: '/rh',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalFinanceiroRoute = PortalFinanceiroRouteImport.update({
  id: '/portal-financeiro',
  path: '/portal-financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const PontoRoute = PontoRouteImport.update({
  id: '/ponto',
  path: '/ponto',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusDocumentosRoute = MeusDocumentosRouteImport.update({
  id: '/meus-documentos',
  path: '/meus-documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GestorRoute = GestorRouteImport.update({
  id: '/gestor',
  path: '/gestor',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RhVtVaRoute = RhVtVaRouteImport.update({
  id: '/vt-va',
  path: '/vt-va',
  getParentRoute: () => RhRoute,
} as any)
const RhSimulacoesRoute = RhSimulacoesRouteImport.update({
  id: '/simulacoes',
  path: '/simulacoes',
  getParentRoute: () => RhRoute,
} as any)
const RhRubricasRoute = RhRubricasRouteImport.update({
  id: '/rubricas',
  path: '/rubricas',
  getParentRoute: () => RhRoute,
} as any)
const RhPessoasRoute = RhPessoasRouteImport.update({
  id: '/pessoas',
  path: '/pessoas',
  getParentRoute: () => RhRoute,
} as any)
const RhMovimentacoesRoute = RhMovimentacoesRouteImport.update({
  id: '/movimentacoes',
  path: '/movimentacoes',
  getParentRoute: () => RhRoute,
} as any)
const RhImportacoesRoute = RhImportacoesRouteImport.update({
  id: '/importacoes',
  path: '/importacoes',
  getParentRoute: () => RhRoute,
} as any)
const RhFuncionariosRoute = RhFuncionariosRouteImport.update({
  id: '/funcionarios',
  path: '/funcionarios',
  getParentRoute: () => RhRoute,
} as any)
const RhFolhasEspeciaisRoute = RhFolhasEspeciaisRouteImport.update({
  id: '/folhas-especiais',
  path: '/folhas-especiais',
  getParentRoute: () => RhRoute,
} as any)
const RhFeriasRoute = RhFeriasRouteImport.update({
  id: '/ferias',
  path: '/ferias',
  getParentRoute: () => RhRoute,
} as any)
const RhFamiliaRoute = RhFamiliaRouteImport.update({
  id: '/familia',
  path: '/familia',
  getParentRoute: () => RhRoute,
} as any)
const RhEventosFuncionaisRoute = RhEventosFuncionaisRouteImport.update({
  id: '/eventos-funcionais',
  path: '/eventos-funcionais',
  getParentRoute: () => RhRoute,
} as any)
const RhEscalasRoute = RhEscalasRouteImport.update({
  id: '/escalas',
  path: '/escalas',
  getParentRoute: () => RhRoute,
} as any)
const RhCiclosRoute = RhCiclosRouteImport.update({
  id: '/ciclos',
  path: '/ciclos',
  getParentRoute: () => RhRoute,
} as any)
const GestorLrfRoute = GestorLrfRouteImport.update({
  id: '/lrf',
  path: '/lrf',
  getParentRoute: () => GestorRoute,
} as any)
const GestorAssistenteRoute = GestorAssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => GestorRoute,
} as any)
const ContaSegurancaRoute = ContaSegurancaRouteImport.update({
  id: '/conta/seguranca',
  path: '/conta/seguranca',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/admin/usuarios',
  path: '/admin/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSegurancaRoute = AdminSegurancaRouteImport.update({
  id: '/admin/seguranca',
  path: '/admin/seguranca',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMigracaoHistoricaRoute = AdminMigracaoHistoricaRouteImport.update({
  id: '/admin/migracao-historica',
  path: '/admin/migracao-historica',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEstruturaRoute = AdminEstruturaRouteImport.update({
  id: '/admin/estrutura',
  path: '/admin/estrutura',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDataMartRoute = AdminDataMartRouteImport.update({
  id: '/admin/data-mart',
  path: '/admin/data-mart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/admin/configuracoes',
  path: '/admin/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditoriaRoute = AdminAuditoriaRouteImport.update({
  id: '/admin/auditoria',
  path: '/admin/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const RhFuncionariosIdRoute = RhFuncionariosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RhFuncionariosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/gestor': typeof GestorRouteWithChildren
  '/login': typeof LoginRoute
  '/meus-documentos': typeof MeusDocumentosRoute
  '/ponto': typeof PontoRoute
  '/portal-financeiro': typeof PortalFinanceiroRoute
  '/rh': typeof RhRouteWithChildren
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/data-mart': typeof AdminDataMartRoute
  '/admin/estrutura': typeof AdminEstruturaRoute
  '/admin/migracao-historica': typeof AdminMigracaoHistoricaRoute
  '/admin/seguranca': typeof AdminSegurancaRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/conta/seguranca': typeof ContaSegurancaRoute
  '/gestor/assistente': typeof GestorAssistenteRoute
  '/gestor/lrf': typeof GestorLrfRoute
  '/rh/ciclos': typeof RhCiclosRoute
  '/rh/escalas': typeof RhEscalasRoute
  '/rh/eventos-funcionais': typeof RhEventosFuncionaisRoute
  '/rh/familia': typeof RhFamiliaRoute
  '/rh/ferias': typeof RhFeriasRoute
  '/rh/folhas-especiais': typeof RhFolhasEspeciaisRoute
  '/rh/funcionarios': typeof RhFuncionariosRouteWithChildren
  '/rh/importacoes': typeof RhImportacoesRoute
  '/rh/movimentacoes': typeof RhMovimentacoesRoute
  '/rh/pessoas': typeof RhPessoasRoute
  '/rh/rubricas': typeof RhRubricasRoute
  '/rh/simulacoes': typeof RhSimulacoesRoute
  '/rh/vt-va': typeof RhVtVaRoute
  '/rh/funcionarios/$id': typeof RhFuncionariosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/gestor': typeof GestorRouteWithChildren
  '/login': typeof LoginRoute
  '/meus-documentos': typeof MeusDocumentosRoute
  '/ponto': typeof PontoRoute
  '/portal-financeiro': typeof PortalFinanceiroRoute
  '/rh': typeof RhRouteWithChildren
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/data-mart': typeof AdminDataMartRoute
  '/admin/estrutura': typeof AdminEstruturaRoute
  '/admin/migracao-historica': typeof AdminMigracaoHistoricaRoute
  '/admin/seguranca': typeof AdminSegurancaRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/conta/seguranca': typeof ContaSegurancaRoute
  '/gestor/assistente': typeof GestorAssistenteRoute
  '/gestor/lrf': typeof GestorLrfRoute
  '/rh/ciclos': typeof RhCiclosRoute
  '/rh/escalas': typeof RhEscalasRoute
  '/rh/eventos-funcionais': typeof RhEventosFuncionaisRoute
  '/rh/familia': typeof RhFamiliaRoute
  '/rh/ferias': typeof RhFeriasRoute
  '/rh/folhas-especiais': typeof RhFolhasEspeciaisRoute
  '/rh/funcionarios': typeof RhFuncionariosRouteWithChildren
  '/rh/importacoes': typeof RhImportacoesRoute
  '/rh/movimentacoes': typeof RhMovimentacoesRoute
  '/rh/pessoas': typeof RhPessoasRoute
  '/rh/rubricas': typeof RhRubricasRoute
  '/rh/simulacoes': typeof RhSimulacoesRoute
  '/rh/vt-va': typeof RhVtVaRoute
  '/rh/funcionarios/$id': typeof RhFuncionariosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/gestor': typeof GestorRouteWithChildren
  '/login': typeof LoginRoute
  '/meus-documentos': typeof MeusDocumentosRoute
  '/ponto': typeof PontoRoute
  '/portal-financeiro': typeof PortalFinanceiroRoute
  '/rh': typeof RhRouteWithChildren
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/data-mart': typeof AdminDataMartRoute
  '/admin/estrutura': typeof AdminEstruturaRoute
  '/admin/migracao-historica': typeof AdminMigracaoHistoricaRoute
  '/admin/seguranca': typeof AdminSegurancaRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/conta/seguranca': typeof ContaSegurancaRoute
  '/gestor/assistente': typeof GestorAssistenteRoute
  '/gestor/lrf': typeof GestorLrfRoute
  '/rh/ciclos': typeof RhCiclosRoute
  '/rh/escalas': typeof RhEscalasRoute
  '/rh/eventos-funcionais': typeof RhEventosFuncionaisRoute
  '/rh/familia': typeof RhFamiliaRoute
  '/rh/ferias': typeof RhFeriasRoute
  '/rh/folhas-especiais': typeof RhFolhasEspeciaisRoute
  '/rh/funcionarios': typeof RhFuncionariosRouteWithChildren
  '/rh/importacoes': typeof RhImportacoesRoute
  '/rh/movimentacoes': typeof RhMovimentacoesRoute
  '/rh/pessoas': typeof RhPessoasRoute
  '/rh/rubricas': typeof RhRubricasRoute
  '/rh/simulacoes': typeof RhSimulacoesRoute
  '/rh/vt-va': typeof RhVtVaRoute
  '/rh/funcionarios/$id': typeof RhFuncionariosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/gestor'
    | '/login'
    | '/meus-documentos'
    | '/ponto'
    | '/portal-financeiro'
    | '/rh'
    | '/admin/auditoria'
    | '/admin/configuracoes'
    | '/admin/data-mart'
    | '/admin/estrutura'
    | '/admin/migracao-historica'
    | '/admin/seguranca'
    | '/admin/usuarios'
    | '/conta/seguranca'
    | '/gestor/assistente'
    | '/gestor/lrf'
    | '/rh/ciclos'
    | '/rh/escalas'
    | '/rh/eventos-funcionais'
    | '/rh/familia'
    | '/rh/ferias'
    | '/rh/folhas-especiais'
    | '/rh/funcionarios'
    | '/rh/importacoes'
    | '/rh/movimentacoes'
    | '/rh/pessoas'
    | '/rh/rubricas'
    | '/rh/simulacoes'
    | '/rh/vt-va'
    | '/rh/funcionarios/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/gestor'
    | '/login'
    | '/meus-documentos'
    | '/ponto'
    | '/portal-financeiro'
    | '/rh'
    | '/admin/auditoria'
    | '/admin/configuracoes'
    | '/admin/data-mart'
    | '/admin/estrutura'
    | '/admin/migracao-historica'
    | '/admin/seguranca'
    | '/admin/usuarios'
    | '/conta/seguranca'
    | '/gestor/assistente'
    | '/gestor/lrf'
    | '/rh/ciclos'
    | '/rh/escalas'
    | '/rh/eventos-funcionais'
    | '/rh/familia'
    | '/rh/ferias'
    | '/rh/folhas-especiais'
    | '/rh/funcionarios'
    | '/rh/importacoes'
    | '/rh/movimentacoes'
    | '/rh/pessoas'
    | '/rh/rubricas'
    | '/rh/simulacoes'
    | '/rh/vt-va'
    | '/rh/funcionarios/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/gestor'
    | '/login'
    | '/meus-documentos'
    | '/ponto'
    | '/portal-financeiro'
    | '/rh'
    | '/admin/auditoria'
    | '/admin/configuracoes'
    | '/admin/data-mart'
    | '/admin/estrutura'
    | '/admin/migracao-historica'
    | '/admin/seguranca'
    | '/admin/usuarios'
    | '/conta/seguranca'
    | '/gestor/assistente'
    | '/gestor/lrf'
    | '/rh/ciclos'
    | '/rh/escalas'
    | '/rh/eventos-funcionais'
    | '/rh/familia'
    | '/rh/ferias'
    | '/rh/folhas-especiais'
    | '/rh/funcionarios'
    | '/rh/importacoes'
    | '/rh/movimentacoes'
    | '/rh/pessoas'
    | '/rh/rubricas'
    | '/rh/simulacoes'
    | '/rh/vt-va'
    | '/rh/funcionarios/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  GestorRoute: typeof GestorRouteWithChildren
  LoginRoute: typeof LoginRoute
  MeusDocumentosRoute: typeof MeusDocumentosRoute
  PontoRoute: typeof PontoRoute
  PortalFinanceiroRoute: typeof PortalFinanceiroRoute
  RhRoute: typeof RhRouteWithChildren
  AdminAuditoriaRoute: typeof AdminAuditoriaRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminDataMartRoute: typeof AdminDataMartRoute
  AdminEstruturaRoute: typeof AdminEstruturaRoute
  AdminMigracaoHistoricaRoute: typeof AdminMigracaoHistoricaRoute
  AdminSegurancaRoute: typeof AdminSegurancaRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  ContaSegurancaRoute: typeof ContaSegurancaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rh': {
      id: '/rh'
      path: '/rh'
      fullPath: '/rh'
      preLoaderRoute: typeof RhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal-financeiro': {
      id: '/portal-financeiro'
      path: '/portal-financeiro'
      fullPath: '/portal-financeiro'
      preLoaderRoute: typeof PortalFinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ponto': {
      id: '/ponto'
      path: '/ponto'
      fullPath: '/ponto'
      preLoaderRoute: typeof PontoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-documentos': {
      id: '/meus-documentos'
      path: '/meus-documentos'
      fullPath: '/meus-documentos'
      preLoaderRoute: typeof MeusDocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestor': {
      id: '/gestor'
      path: '/gestor'
      fullPath: '/gestor'
      preLoaderRoute: typeof GestorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rh/vt-va': {
      id: '/rh/vt-va'
      path: '/vt-va'
      fullPath: '/rh/vt-va'
      preLoaderRoute: typeof RhVtVaRouteImport
      parentRoute: typeof RhRoute
    }
    '/rh/simulacoes': {
      id: '/rh/simulacoes'
      path: '/simulacoes'
      fullPath: '/rh/simulacoes'
      preLoaderRoute: typeof RhSimulacoesRouteImport
      parentRoute: typeof RhRoute
    }
    '/rh/rubricas': {
      id: '/rh/rubricas'
      path: '/rubricas'
      fullPath: '/rh/rubricas'
      preLoaderRoute: typeof RhRubricasRouteImport
      parentRoute: typeof RhRoute
    }
    '/rh/pessoas': {
      id: '/rh/pessoas'
      path: '/pessoas'
      fullPath: '/rh/pessoas'
      preLoaderRoute: typeof RhPessoasRouteImport
      parentRoute: typeof RhRoute
    }
    '/rh/movimentacoes': {
      id: '/rh/movimentacoes'
      path: '/movimentacoes'
      fullPath: '/rh/movimentacoes'
      preLoaderRoute: typeof RhMovimentacoesRouteImport
      parentRoute: typeof RhRoute
    }
    '/rh/importacoes': {
      id: '/rh/importacoes'
      path: '/importacoes'
      fullPath: '/rh/importacoes'
      preLoaderRoute: typeof RhImportacoesRouteImport
      parentRoute: typeof RhRoute
    }
    '/rh/funcionarios': {
      id: '/rh/funcionarios'
      path: '/funcionarios'
      fullPath: '/rh/funcionarios'
      preLoaderRoute: typeof RhFuncionariosRouteImport
      parentRoute: typeof RhRoute
    }
    '/rh/folhas-especiais': {
      id: '/rh/folhas-especiais'
      path: '/folhas-especiais'
      fullPath: '/rh/folhas-especiais'
      preLoaderRoute: typeof RhFolhasEspeciaisRouteImport
      parentRoute: typeof RhRoute
    }
    '/rh/ferias': {
      id: '/rh/ferias'
      path: '/ferias'
      fullPath: '/rh/ferias'
      preLoaderRoute: typeof RhFeriasRouteImport
      parentRoute: typeof RhRoute
    }
    '/rh/familia': {
      id: '/rh/familia'
      path: '/familia'
      fullPath: '/rh/familia'
      preLoaderRoute: typeof RhFamiliaRouteImport
      parentRoute: typeof RhRoute
    }
    '/rh/eventos-funcionais': {
      id: '/rh/eventos-funcionais'
      path: '/eventos-funcionais'
      fullPath: '/rh/eventos-funcionais'
      preLoaderRoute: typeof RhEventosFuncionaisRouteImport
      parentRoute: typeof RhRoute
    }
    '/rh/escalas': {
      id: '/rh/escalas'
      path: '/escalas'
      fullPath: '/rh/escalas'
      preLoaderRoute: typeof RhEscalasRouteImport
      parentRoute: typeof RhRoute
    }
    '/rh/ciclos': {
      id: '/rh/ciclos'
      path: '/ciclos'
      fullPath: '/rh/ciclos'
      preLoaderRoute: typeof RhCiclosRouteImport
      parentRoute: typeof RhRoute
    }
    '/gestor/lrf': {
      id: '/gestor/lrf'
      path: '/lrf'
      fullPath: '/gestor/lrf'
      preLoaderRoute: typeof GestorLrfRouteImport
      parentRoute: typeof GestorRoute
    }
    '/gestor/assistente': {
      id: '/gestor/assistente'
      path: '/assistente'
      fullPath: '/gestor/assistente'
      preLoaderRoute: typeof GestorAssistenteRouteImport
      parentRoute: typeof GestorRoute
    }
    '/conta/seguranca': {
      id: '/conta/seguranca'
      path: '/conta/seguranca'
      fullPath: '/conta/seguranca'
      preLoaderRoute: typeof ContaSegurancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/seguranca': {
      id: '/admin/seguranca'
      path: '/admin/seguranca'
      fullPath: '/admin/seguranca'
      preLoaderRoute: typeof AdminSegurancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/migracao-historica': {
      id: '/admin/migracao-historica'
      path: '/admin/migracao-historica'
      fullPath: '/admin/migracao-historica'
      preLoaderRoute: typeof AdminMigracaoHistoricaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/estrutura': {
      id: '/admin/estrutura'
      path: '/admin/estrutura'
      fullPath: '/admin/estrutura'
      preLoaderRoute: typeof AdminEstruturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/data-mart': {
      id: '/admin/data-mart'
      path: '/admin/data-mart'
      fullPath: '/admin/data-mart'
      preLoaderRoute: typeof AdminDataMartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/admin/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/auditoria': {
      id: '/admin/auditoria'
      path: '/admin/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AdminAuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rh/funcionarios/$id': {
      id: '/rh/funcionarios/$id'
      path: '/$id'
      fullPath: '/rh/funcionarios/$id'
      preLoaderRoute: typeof RhFuncionariosIdRouteImport
      parentRoute: typeof RhFuncionariosRoute
    }
  }
}

interface GestorRouteChildren {
  GestorAssistenteRoute: typeof GestorAssistenteRoute
  GestorLrfRoute: typeof GestorLrfRoute
}

const GestorRouteChildren: GestorRouteChildren = {
  GestorAssistenteRoute: GestorAssistenteRoute,
  GestorLrfRoute: GestorLrfRoute,
}

const GestorRouteWithChildren =
  GestorRoute._addFileChildren(GestorRouteChildren)

interface RhFuncionariosRouteChildren {
  RhFuncionariosIdRoute: typeof RhFuncionariosIdRoute
}

const RhFuncionariosRouteChildren: RhFuncionariosRouteChildren = {
  RhFuncionariosIdRoute: RhFuncionariosIdRoute,
}

const RhFuncionariosRouteWithChildren = RhFuncionariosRoute._addFileChildren(
  RhFuncionariosRouteChildren,
)

interface RhRouteChildren {
  RhCiclosRoute: typeof RhCiclosRoute
  RhEscalasRoute: typeof RhEscalasRoute
  RhEventosFuncionaisRoute: typeof RhEventosFuncionaisRoute
  RhFamiliaRoute: typeof RhFamiliaRoute
  RhFeriasRoute: typeof RhFeriasRoute
  RhFolhasEspeciaisRoute: typeof RhFolhasEspeciaisRoute
  RhFuncionariosRoute: typeof RhFuncionariosRouteWithChildren
  RhImportacoesRoute: typeof RhImportacoesRoute
  RhMovimentacoesRoute: typeof RhMovimentacoesRoute
  RhPessoasRoute: typeof RhPessoasRoute
  RhRubricasRoute: typeof RhRubricasRoute
  RhSimulacoesRoute: typeof RhSimulacoesRoute
  RhVtVaRoute: typeof RhVtVaRoute
}

const RhRouteChildren: RhRouteChildren = {
  RhCiclosRoute: RhCiclosRoute,
  RhEscalasRoute: RhEscalasRoute,
  RhEventosFuncionaisRoute: RhEventosFuncionaisRoute,
  RhFamiliaRoute: RhFamiliaRoute,
  RhFeriasRoute: RhFeriasRoute,
  RhFolhasEspeciaisRoute: RhFolhasEspeciaisRoute,
  RhFuncionariosRoute: RhFuncionariosRouteWithChildren,
  RhImportacoesRoute: RhImportacoesRoute,
  RhMovimentacoesRoute: RhMovimentacoesRoute,
  RhPessoasRoute: RhPessoasRoute,
  RhRubricasRoute: RhRubricasRoute,
  RhSimulacoesRoute: RhSimulacoesRoute,
  RhVtVaRoute: RhVtVaRoute,
}

const RhRouteWithChildren = RhRoute._addFileChildren(RhRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  GestorRoute: GestorRouteWithChildren,
  LoginRoute: LoginRoute,
  MeusDocumentosRoute: MeusDocumentosRoute,
  PontoRoute: PontoRoute,
  PortalFinanceiroRoute: PortalFinanceiroRoute,
  RhRoute: RhRouteWithChildren,
  AdminAuditoriaRoute: AdminAuditoriaRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminDataMartRoute: AdminDataMartRoute,
  AdminEstruturaRoute: AdminEstruturaRoute,
  AdminMigracaoHistoricaRoute: AdminMigracaoHistoricaRoute,
  AdminSegurancaRoute: AdminSegurancaRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  ContaSegurancaRoute: ContaSegurancaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
